name: wass
channels:
  - conda-forge
dependencies:
  - python=3.9.14
  - ipython
  - jupyter
  - jupyterlab
  - datashader
  - pocl
  - numpy
  - numba=0.56.4
  - scipy
  - pandas
  - xarray
  - pint-xarray
  - pint
  - matplotlib
  - hvplot
  - cmocean
  - scikit-learn
  - scikit-image
  - nbconvert
  - cftime
  - cf_xarray
  - netcdf4
  - opencv
  - ipympl
  - ipywidgets=8.0.4
  - h5netcdf
  - tqdm
